name: C/C++ CI

on:
  push:
    branches:
      - main

jobs:

  build-debug:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10 git cmake python3-pip libsdl2-dev libglm-dev
      
      - name: Setup OpenGL
        run: |
          sudo apt install mesa-utils linux-generic xserver-xorg-core xserver-xorg xserver-xorg-video-all xserver-xorg-input-all libwayland-egl1-mesa
          /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX
          export SDL_VIDEODRIVER=x11
          export DISPLAY=:99.0

      - name: CMake Configure
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/test_install -DBUILD_GLIDER_TESTS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-10
      
      - name: Build
        run: cmake --build build --verbose
        
      - name: Run Tests
        run: |
          ls build
          ctest --test-dir build -C Debug --output-on-failure
  
  # build-relese:

  #   runs-on: ubuntu-latest
  #   needs: build-debug
    
  #   steps:

  #     - name: Reconfigure CMake
  #       run: |
  #         rm -rf *
  #         rm -rf .*
  #         cmake ..
      
  #     - name: Build
  #       run: cmake --build . --verbose
      
  #     - name: Install
  #       run: |
  #         cmake --install . --prefix "$HOME/GLider/usr"
  #         cp -r ../debian/. ~/GLider/DEBIAN/
      
  #     - name: Create Debian Package
  #       run: |
  #         cd ~
  #         dpkg-deb --build GLider
  

