name: C/C++ CI

on:
  push:
    branches:
      - main

jobs:

  build-debug:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install gcc g++ git cmake python3-pip libsdl2-dev libglm-dev

      - name: CMake Configure
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/test_install -DBUILD_TESTS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug
      
      - name: Build
        run: cmake --build build --verbose
        
      - name: Run Tests
        run: ctest -C Debug -T test --output-on-failure --test-dir build
  
  # build-relese:

  #   runs-on: ubuntu-latest
  #   needs: build-debug
    
  #   steps:

  #     - name: Reconfigure CMake
  #       run: |
  #         rm -rf *
  #         rm -rf .*
  #         cmake ..
      
  #     - name: Build
  #       run: cmake --build . --verbose
      
  #     - name: Install
  #       run: |
  #         cmake --install . --prefix "$HOME/GLider/usr"
  #         cp -r ../debian/. ~/GLider/DEBIAN/
      
  #     - name: Create Debian Package
  #       run: |
  #         cd ~
  #         dpkg-deb --build GLider
  

