name: publish
on:
  push:
    branches:
      - dev
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install Doxygen 1.9.2
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
      - name: Generate Documentation
        run: doxygen Doxyfile
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs/html
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}